language: python
python:
  - 3.5
  - 3.6
  - 3.7
install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install -U pytest-cov
  - pip install -U coveralls
  - pip install -U numpy

before_script:
  - py.test dronelanding/tests.py --cov=example

script: py.test dronelanding/tests.py --doctest-modules --pep8 coveralls -v --cov coveralls --cov-report term-missing
after_success:
  - coveralls
