language: python

python:
  - 3.6

addons:
  apt:
    packages:
      - docker-ce

service:
  - docker

cache:
  directories:
    - /home/travis/docker/

before_install:
  - make build

script:
  - docker run -it -v ${PWD}:/training_model francescsco/cnn-singularity:latest

after_success:
  - make push
