language: python

python:
  - 3.6
  - 3.7

install:
  - python --version
  - pip install -U pip
  - pip install -U pytest pytest-cov
  - pip install -U coveralls tqdm
  - pip install -r requirements.txt

before_script:
  # prepare dataset: download and unzip
  - landing_script=$(find . -name "landingzone.py")
  - python3 downloadmanager.py
  - unzip dataset.zip
  # clean files
  - find . -type f -name '._*' -delete
  - find . -type d -name '__MACOSX' -delete
  # get paths for file and folder
  - echo "Serching for datasetfolder"
  - datasetpath=$(find $PWD -name "landingzone")
  - echo "found dataset folder at ${datasetpath}"
  - echo "Searching for annotations file"
  - datasetannotations=$(find $PWD -name "annotations.json")
  - echo "found dataset annotaions at ${datasetannotations}"

script:
  - coverage run ${landing_script} -a ${datasetannotations} -d ${datasetpath} --weights=coco

after_success:
  - coverage report -m
  - coveralls
