dist: xenial
language: python
python:
  - '3.5'
  - '3.6'
  - '3.7'

cache: pip

matrix:
  fast_finish: true


# install requirements
install:
  - pip install --user -r requirements.txt
  - pip install python-coveralls

# command to run tests
script:
  - test2.py

after_success:
  - coveralls
