language: python
python:
  - 3.5
  - 3.6
  - 3.7
before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install -U pytest-cov
  - pip install -U coveralls
  - pip install -U numpy
install:
  - pip install ".[test]" . # install package + test dependencies
script: pytest --cov=./dronelanding/test.py
after_success:
  - coveralls
