language: python

python:
  - 3.6

addons:
  apt:
    packages:
      - docker-ce

service:
  - docker

cache:
  directories:
    - /home/travis/docker/

before_install:
  - make build

script:
  - coverage run ${landing_script} --annotations ${datasetannotations} --dataset ${datasetpath} --weights=coco
  - coverage run -a ${landing_script} --annotations ${datasetannotations} --dataset ${datasetpath} --weights=imagenet

after_success:
  - make push
