language: python

python:
  - 3.5
  - 3.6
  - 3.7

install:
  - python --version
  - pip install -U pip
  - pip install -U pytest pytest-cov
  - pip install -U coveralls
  - pip install -U 'numpy>1.15.4,<1.17.3' --force-reinstall

before_script:
  - test_file=$(find . -name "test.py")
  - landing_script=$(find . -name "landingzone.py")
  - pytest -v ${test_file}

script:
  - coverage report ${test_file}
  - coverage run ${test_file}
  - coverage run -a ${landing_script}

after_success:
  - coverage report -m
  - coveralls
