dist: xenial
language: python
python:
  - '3.5'
  - '3.6'
  - '3.7'

cache:
  pip: true
  directories:
    - $HOME/.ccache
    - $HOME/.cache/matplotlib

matrix:
  fast_finish: true


# install requirements
install:
  - pip install -r requirements.txt
  - pip install python-coveralls

# command to run tests
script:
  - python3 main.py

after_success:
  - coveralls
