language: python

python:
  - 3.6

addons:
  apt:
    packages:
      - docker-ce

service:
- docker

cache:
  directories:
  - /home/travis/docker/


before_install:
  - docker build -t unitntest .

script:
- docker run -it -v ${PWD}:/training_model unitntest
