language: python

python:
  - 3.5
  - 3.6
  - 3.7

install:
  - python --version
  - pip install -U pip
  - pip install -U pytest pytest-cov
  - pip install -U coveralls
  - pip install -U numpy

before_script:
  - test_file=$(find . -name "test.py")
  - coverage run ${test_file}

script:
  - test_folder=$(find . -name "*.py")
  - coverage report ${test_file} ${test_folder}
  - coverage run ${test_file} ${test_folder}

after_success:
  - coveralls
