language: python

python:
  - 3.5
  - 3.5.2
  - 3.6
  - 3.7
  - 3.7.2

install:
  - python --version
  - pip install -U pip
  - pip install -U pytest pytest-cov
  - pip install -U coveralls tqdm
  - pip install -r requirements.txt
  - pip list

before_script:
  # install package
  - python3 setup.py install

script:
  - make test

after_success:
  - coverage report -m
  - coveralls
