language: python
python:
  - 3.5
  - 3.6
  - 3.7
install:
  - python --version
  - pip install -U pip
  - pip install -U pytest pytest-cov
  - pip install -U coveralls
  - pip install -U numpy

before_script:
  - test_file=$(find . -name "test.py")
  - py.test ${test_file}

script: py.test ${test_file} #--doctest-modules --pep8 coveralls -v --cov coveralls --cov-report term-missing
after_success:
  - coveralls
