language: python

python:
  - 3.5
  - 3.5.2
  - 3.6
  - 3.7
  - 3.7.2

install:
  - python --version
  - pip install -U pip
  - pip install -U pytest pytest-cov
  - pip install -U coveralls tqdm
  - pip install -r requirements.txt
  - pip list

before_script:
  # prepare dataset: download and unzip
  - landing_script=$(find . -name "landingzone.py")
  - python3 downloadmanager.py
  - unzip -qq dataset.zip
  # clean files
  - find . -type f -name '._*' -delete
  - delfolder=$(find . -type d -name '__MACOSX')
  - rm -rf ${delfolder}
  # get paths for file and folder
  - echo "Serching for datasetfolder"
  - datasetpath=$(find $PWD -name "landingzone")
  - echo "found dataset folder at ${datasetpath}"
  - echo "Searching for annotations file"
  - datasetannotations=$(find $PWD -name "annotations.json")
  - echo "found dataset annotaions at ${datasetannotations}"
  # install package
  -  python3 setup.py install

script:
  - coverage run downloadmanager.py
  - coverage run -a preparedata.py --dataset ${datasetpath} --split 35
  - coverage run -a xml_to_csv.py --annotations ${datasetpath}/train --output_csv train_labels.csv
  - coverage run -a xml_to_csv.py --annotations ${datasetpath}/validate --output_csv validate_labels.csv
  - coverage run -a ${landing_script} train --annotations ${datasetannotations} --dataset ${datasetpath} --weights=coco
  - coverage run -a ${landing_script} train --annotations ${datasetannotations} --dataset ${datasetpath} --weights=imagenet


after_success:
  - coverage report -m
  - coveralls
